name: Preprocessing Data

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run preprocessing script
        run: |
          cd preprocessing
          python automate_Felda-Ega.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: preprocessing-data
          path: preprocessing/breast_cancer_preprocessing.csv
